services:

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task_queue_network

    
  worker:
    build:
      context: .
      dockerfile: dockerfile.worker
    container_name: worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    networks:
      - task_queue_network
    volumes:
      - .:/app

  beat:
    build:
      context: .
      dockerfile: dockerfile.worker
    container_name: beat
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
      - worker
    networks:
      - task_queue_network
    volumes:
      - .:/app

  client:
    build:
      context: .
      dockerfile: dockerfile.client
    container_name: client
    depends_on:
      - worker
    networks:
      - task_queue_network
    volumes:
      - .:/app

networks:
  task_queue_network:
    driver: bridge